### ISSUE TITLE
NullReference Exception

### ISSUE THREAD

**Issue by JannyM85** [tanveery/recaptcha-net#23]
Hi i create ActonFilterAttribute and i have problem with null reference exception in recaptchaHelper.VerifyRecaptchaResponse().
`public class IsValidCaptcha : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            var controller = (filterContext.Controller as Controller);
            if (controller == null)
                return;

            var ms = filterContext.Controller.ViewData.ModelState;

            var recaptchaHelper = controller.GetRecaptchaVerificationHelper();
            if (String.IsNullOrEmpty(recaptchaHelper.Response))
            {
                ms.AddModelError("", "Captcha answer cannot be empty.");
            }
            var recaptchaResult = recaptchaHelper.VerifyRecaptchaResponse();
            if (recaptchaResult != RecaptchaVerificationResult.Success)
            {
                ms.AddModelError("", "Incorrect captcha answer.");
            }
        }
    }`
   at Recaptcha.Web.RecaptchaVerificationHelper.VerifyRecpatcha2Response(String privateKey)
   at SteamMarket.Logic.Common.Filters.IsValidCaptcha.OnActionExecuting(ActionExecutingContext filterContext) in G:\___ORIK\SteamMarket\SteamMarket\SteamMarket.Logic\Common\Filters\IsValidCaptcha.cs:line 23
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)

**Comment by Sire** [comment]
I get this as well, on a few number of requests every day (I guess 5% at the most).

We're just using regular ASP.NET.

`System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
at Recaptcha.Web.RecaptchaVerificationHelper.VerifyRecpatcha2Response(String privateKey)
at Recaptcha.Web.RecaptchaVerificationHelper.VerifyRecaptchaResponse()
at Recaptcha.Web.UI.Controls.Recaptcha.Verify()
at Web.Controls.RecaptchaHelper.Validate(Recaptcha recaptcha, String& errorMsg) in RecaptchaHelper.cs:line 20
at Web.User.btnSubmit_Click(Object sender, EventArgs e) in User.aspx.cs:line 58
`

**Comment by gir489** [comment]
I am also getting this error.

[NullReferenceException: Object reference not set to an instance of an object.]
   Recaptcha.Web.RecaptchaVerificationHelper.VerifyRecpatcha2Response(String privateKey) +895
   Recaptcha.Web.RecaptchaVerificationHelper.VerifyRecaptchaResponse() +243
   com.sac.WebLookup.Controls.Recaptcha.Validate() in c:\Users\robert\Source\Repos\CDT\Verification\SystemAutomation.Verification.WebControls\Source\Recaptcha.cs:98
   System.Web.UI.Page.Validate() +289
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3804

**Comment by gir489** [comment]
I have determined how to reproduce this, if the developer is interested.

Implement IValidator, and call the validation twice, one on PostBack, and once during the normal validation stage. Calling the Verify method on base.Verify() the 2nd time, causes a NullRefrenceException.

**Comment by yunuskiran** [comment]
what is the solution ?

**Comment by Sire** [comment]
@tanveery I can try to fix it but I'm out of ideas. Any help?
